services:
  - type: web
    name: your-app-name
    env: python
    buildCommand: ./build.sh
    startCommand: gunicorn Mindcare.eyt.wsgi:application
    disk:
      name: media
      mountPath: /app/media
      sizeGB: 1
